image: Visual Studio 2019

install:
  - git submodule update --init --recursive
  - cd contrib
  - appveyor DownloadFile https://github.com/lemourin/libcloudstorage/releases/download/1.9/win32-x64-vs2019.7z
  - 7z x win32-x64-vs2019.7z
  - cd ..

platform: x64
configuration: Release

build:
  project: build\cloudstorage.sln

before_build:
  - mkdir build
  - cd build
  - set PREFIX_PATH_DEBUG=%cd%\..\contrib\win32\x64\Debug
  - set PREFIX_PATH_RELEASE=%cd%\..\contrib\win32\x64\Release
  - cmake .. -DPREFIX_PATH_DEBUG="%PREFIX_PATH_DEBUG%" -DPREFIX_PATH_RELEASE="%PREFIX_PATH_RELEASE%"
      -DCMAKE_EXE_LINKER_FLAGS_DEBUG="-debug -incremental -libpath:%PREFIX_PATH_DEBUG%\lib libssl.lib libcrypto.lib winhttp.lib nghttp2.lib opengl32.lib avrt.lib secur32.lib libxml2_a.lib zlibstaticd.lib ass.lib harfbuzz.lib libfribidi.lib dwrite.lib"
      -DCMAKE_EXE_LINKER_FLAGS_RELEASE="-incremental:no -libpath:%PREFIX_PATH_RELEASE%\lib libssl.lib libcrypto.lib winhttp.lib nghttp2.lib opengl32.lib avrt.lib secur32.lib libxml2_a.lib zlibstatic.lib ass.lib harfbuzz.lib libfribidi.lib dwrite.lib"
  - cd ..

test_script:
  - msbuild build/RUN_TESTS.vcxproj

artifacts:
  - path: build\bin\cloudbrowser\$(configuration)\cloudbrowser.exe
    name: cloudbrowser-win32

deploy:
  provider: GitHub
  artifact: cloudbrowser-win32
  auth_token:
    secure: kSr0k5pxggXRrdpJ+zcVKsQtMLSBOKVA0609omsG+DL9U4/35vuC5ntlA0yqFSfm
  on:
    appveyor_repo_tag: true
